### ISSUE TITLE
image

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1480-MVAghsurface#1]
![mvaghsurface-1](https://cloud.githubusercontent.com/assets/14127572/9930813/cd8973f6-5d36-11e5-965c-9e99bbead80c.png)

**Comment by Tdannen** [comment]
Description of plot is missing.

**Comment by polarstern** [comment]
Done.
![mvaghsurface-1](https://cloud.githubusercontent.com/assets/14127572/9980928/33f2fd16-5fac-11e5-9ef7-f713f77cc8ff.png)

**Comment by polarstern** [comment]
Please update image here and in "Ready"

**Comment by Tdannen** [comment]
done
